# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ge < Formula
  desc "Git Extension CLI — multi-account, worktree, and branch management"
  homepage "https://github.com/isac7722/git-extension"
  version "2.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isac7722/git-extension/releases/download/v2.9.0/git-extension_2.9.0_darwin_amd64.tar.gz"
      sha256 "212f21d1c240d1bec90e7ff677de62420eeb81c9bcc163a9ff25aa4570cd50c4"

      define_method(:install) do
        bin.install "ge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isac7722/git-extension/releases/download/v2.9.0/git-extension_2.9.0_darwin_arm64.tar.gz"
      sha256 "7ae8fd9ad641fdc53f8b63c2674fcbc19ed00fa84ab108d996fb41cefc12332e"

      define_method(:install) do
        bin.install "ge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isac7722/git-extension/releases/download/v2.9.0/git-extension_2.9.0_linux_amd64.tar.gz"
      sha256 "4a16479c559070e873b1a3065c0f7574f95b9ab27c83b31c437c74f60e884859"
      define_method(:install) do
        bin.install "ge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isac7722/git-extension/releases/download/v2.9.0/git-extension_2.9.0_linux_arm64.tar.gz"
      sha256 "9aafecf45a8dbeae8040bad201173e67a2b9ddb1a40be6b9d400e24fd968dcf0"
      define_method(:install) do
        bin.install "ge"
      end
    end
  end

  test do
    system "#{bin}/ge", "version"
  end
end
