# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ge < Formula
  desc "Git Extension CLI — multi-account, worktree, and branch management"
  homepage "https://github.com/isac7722/git-extension"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isac7722/git-extension/releases/download/v1.0.0/git-extension_1.0.0_darwin_amd64.tar.gz"
      sha256 "4985c8752d51927c7df8cb1990370baaa954461e162ed17b711dd589cd6f21a4"

      define_method(:install) do
        bin.install "ge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isac7722/git-extension/releases/download/v1.0.0/git-extension_1.0.0_darwin_arm64.tar.gz"
      sha256 "85dfae3014417a46f59cc0e8311de37da1fe09fc354c3f2d380c52b28a895807"

      define_method(:install) do
        bin.install "ge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isac7722/git-extension/releases/download/v1.0.0/git-extension_1.0.0_linux_amd64.tar.gz"
      sha256 "9d1136df8f891e6d701167e664d269813968d50e85bdab8aa841bf1ed1053c52"
      define_method(:install) do
        bin.install "ge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isac7722/git-extension/releases/download/v1.0.0/git-extension_1.0.0_linux_arm64.tar.gz"
      sha256 "817bcf359cd16d826a9ec52547715ffcad5da5a2f9093d0f8a9549360cfa8d06"
      define_method(:install) do
        bin.install "ge"
      end
    end
  end

  test do
    system "#{bin}/ge", "version"
  end
end
