# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitExtension < Formula
  desc "Git Extension CLI — multi-account, worktree, and branch management"
  homepage "https://github.com/isac7722/git-extension"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isac7722/git-extension/releases/download/v1.0.0/git-extension_1.0.0_darwin_amd64.tar.gz"
      sha256 "3e6085e26ab76e5185cc0df861a165aa6e37b9cbb8aafe82ee8ea5b018a28d0a"

      define_method(:install) do
        bin.install "ge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isac7722/git-extension/releases/download/v1.0.0/git-extension_1.0.0_darwin_arm64.tar.gz"
      sha256 "7f38a4959f631f5edb97cfd0c68659dabff531e3707f712043182cd6846b4e99"

      define_method(:install) do
        bin.install "ge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isac7722/git-extension/releases/download/v1.0.0/git-extension_1.0.0_linux_amd64.tar.gz"
      sha256 "6bdb3912b53cf44b98142ec855c5d9b0e168911b8e028ac3b935dc54ec8f79b4"
      define_method(:install) do
        bin.install "ge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isac7722/git-extension/releases/download/v1.0.0/git-extension_1.0.0_linux_arm64.tar.gz"
      sha256 "9ef6ec25cf01600aba890791358ad625d4b2e89ee15718721efd806fa975ff1e"
      define_method(:install) do
        bin.install "ge"
      end
    end
  end

  test do
    system "#{bin}/ge", "version"
  end
end
